language: node.js

node_js:
  - 12

stages:
  - name: deploy
    if: branch = master

before_install:
  - curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o awscli-bundle.zip
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws
  - export PATH=~/bin:$PATH
  - chmod +x ./scripts/aws_config.sh && ./scripts/aws_config.sh
  - chmod +x ./scripts/aws_credentials.sh && ./scripts/aws_credentials.sh
  - echo 'aws-cli installed and configured'

jobs:
  include:
    - stage: deploy
      script:
      - npm install -g serverless
      - cd ./backend && npm install
      - serverless deploy -v